### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by ahmedhus** [raarts/expo-web#2]
Is it possible to use the [Facebook login api](https://docs.expo.io/versions/v27.0.0/sdk/facebook#expofacebookloginwithreadpermissionsasync), or are there any plans to include it the library in the near future?

**Comment by raarts** [comment]
Sure, I use this library with an OpenID Connect provider, but you'll have to implement it yourself. 

I did not have a need for this, I personally use [KeyCloak](https://www.keycloak.org/), which also supports third-party logins like Facebook.

Edit: BTW, this library is currently being integrated with [Expo](https://expo.io/), as soon as that is released, you can use everything Expo offers.

**Comment by ahmedhus** [comment]
Looking forward to see that. Thanks.
